---
title: "Simulating data"
author: "Julia Müller"
date: "29 1 2021"
output: html_document
---

# Workshop data - cats <3 and dogs

```{r}
library(tidyverse)
```


## Corpus data - collocates

collocates from BNC with tags, one position left of CAT/DOG lemma search
```{r}
animal_corpus <- data.frame(
  collocate = c(rep("tom_np1", 9), #cat collocates
              rep("tom_nn1", 8),
              rep("siamese_jj", 17),
              rep("tortoiseshell_nn1", 9),
              rep("ginger_jj", 8),
              rep("purring_jj", 5),
              rep("purring_vvg", 1),
              rep("playing_vvg", 4),
              rep("because_cs", 5),
              rep("contented_jj", 4),
              #dog:
              rep("guide_nn1", 60),
              rep("guide_vv0", 7),
              rep("guide_vvi", 1),
              rep("mad_jj", 52),
              rep("barking_jj", 7),
              rep("barking_vvg", 1),
              rep("barking_np1", 1),
              rep("has_vhz", 19),
              rep("lap_nn1", 17),
              rep("dangerous_jj", 24),
              rep("best_jjt", 4)),
    animal = c(rep("cat", 70), rep("dog", 193))
)

## add: 

# to randomise the order of the rows:
rows <- sample(nrow(animal_corpus))
animal_corpus <- animal_corpus[rows, ]

write.csv2(animal_corpus, "data/cat_dog_corpus_data.csv")
```

## Corpus data - frequency
```{r}
corpus_frequencies <- tibble(
  token = c("mary", "saw", "a", "beautiful", "siamese", "cat", "on", "her", "way", "home", "from", "work", "joshua", "said", "that", "purring", "cats", "are", "one", "of", "the", "most", "relaxing", "things", "to", "him", "there", "was", "contented", "looking", "out", "bookstore", "window", "child", "told", "me", "ginger", "by", "far", "cutest", "them", "all", "large", "tom", "often", "seen", "hanging", "near", "butcher", "shop", "my", "closest", "neighbor", "has", "guide", "dog", "help", "navigate", "students", "were", "worried", "mad", "had", "been", "spotted", "in", "town", "although", "barking", "noisy", "he", "quite", "cute", "grandmother", "lap", "she", "loved", "very", "much", "tracey", "best", "family", "ever", "lisa", "heard", "dogs", "but", "never", "it", "reported", "not", "uncommon", "friend", "jerry", "loves", "lounge", "around", "walk", "through", "woods", "randy", "regal", "baker", "loose", "bay", "louise", "interested", "hear", "how", "adapting", "his", "new", "entire", "city", "talking", "about", "digging", "trash", "cans", "poppy", "read", "newspaper", "identified", "doctor", "keep", "company", "after", "shifts", "georgie", "taken", "part", "contest"),
  frequency = c(
    6791, 24941, 2136923, 8307, 83,
    3788, 717612, 301315, 94797, 419572, 88643, 405,
    193355, 1108428, 114, 1530, 459498, 291900, 3009801, 5973437,
    96938, 665, 40472, 2565070, 152045, 316902, 872620,
    344, 25102, 194816, 27, 9764,
    23486, 34970, 127872, 609, 505413, 39147, 6, 
    165536, 274124, 2136923, 33965, 5249, 36867, 36014,
    2868, 17606, 842, 10310, 145250, 1017,
    11, 253449, 5795, 7780, 36466, 128,
    14395, 309605, 4320, 2921, 415007, 256779,
    1559, 1914216, 17637, 42242, 459, 963,
    633413, 39516, 291, 1306, 1242, 350294, 4525,
    118500, 89035, 553, 34389, 33369, 26201, 1171,
    18754, 4310, 440934, 52643, 1045013, 11548, 447618,
    657, 16202, 513, 1319, 1360, 42775,
    9962, 80364, 2089, 224, 302, 2091,
    2932, 3308, 1414, 8673, 12995, 98107,
    325, 404811, 121905, 4633, 22393, 12779,
    189721, 911, 196, 567, 262, 16913,
    4723, 6177, 10066, 26546, 39326,
    111902, 1152, 81, 34146, 52916, 1624
  )
) %>% 
  arrange(desc(frequency))

write_tsv(corpus_frequencies, "data/corpus_frequencies.txt")
```


## SPR
```{r}
## Design: 
## cond_a is matching collocates (5 about cats, 5 about dogs),
## cond_b is mismatching collocates (5 with dog collocates + cat, 5 with cat collocates + dog)

library(tidytext)

set.seed(2021)

sentence_array <- c("This is a practice sentence to get you used to reading sentences like this.",
                    "Please read as normally as possible.",
                    "The experiment will start on the next sentence.",
                    "Mary saw a beautiful Siamese cat on her way home from work.",
                    "Joshua said that purring cats are one of the most relaxing things to him.",
                    "There was a contented cat looking out from the bookstore window.",
                    "The child told me that ginger cats are by far the cutest of them all.",
                    "A large tom cat was often seen hanging out near the butcher shop.",
                    "My closest neighbor has a guide dog to help him navigate.",
                    "The students were worried that a mad dog had been spotted in town.",
                    "Although the barking dog was noisy, he was quite cute.",
                    "My grandmother had a lap dog that she loved very much.",
                    "Tracey was the best dog Jenny's family ever had.",
                    "Lisa has heard of Siamese dogs, but has never seen one.",
                    "It has been reported that purring dogs are not uncommon.",
                    "My best friend Jerry has a contented dog that loves to lounge around.",
                    "On a walk through the woods, Randy saw a ginger dog that was quite regal.",
                    "The baker said that he saw a tom dog on the loose by the bay.",
                    "Louise was interested to hear how the guide cat was adapting to his new home.",
                    "The entire city was talking about a mad cat that was seen digging through trash cans.",
                    "Poppy read in the newspaper that a barking cat had been identified.",
                    "The doctor had a lap cat to keep her company after her shifts.",
                    "Georgie was the best cat that had ever taken part in the contest.")

RT <- rep(c(
  rnorm(780/12, mean=26, sd= 53), #cond_A_cat
  rnorm(648/12, mean=-65, sd= 35), #cond_A_dog
  rnorm(768/12, mean=356, sd = 54), #cond_B_cat
  rnorm(828/12, mean=469, sd = 112), #cond_B_dog
  rnorm(336/12, mean=600, sd = 70) #practice
  ), 12)

catdog_spr <- tibble(participant = rep(c("Par_A", "Par_B", "Par_C", "Par_D", "Par_E", "Par_F", "Par_G", "Par_H", "Par_I", "Par_J", "Par_K", "Par_M"), each = 23),
       item_type = rep("DashedSentence", 276), 
       cond = rep(c(rep("practice", 3), rep("condA_cat", 5), rep("condA_dog", 5),  rep("condB_cat", 5),  rep("condB_dog", 5)), 12), 
       sentence_num = rep(1:23, 12),
       full_sentence = rep(sentence_array, 12)) %>% 
  unnest_tokens(word, full_sentence, to_lower = FALSE, drop = FALSE) %>%
  arrange(cond) 

# had to interrupt here because you refer to nrow(catdog_spr) which hasn't been created yet
catdog_spr <- catdog_spr %>% 
  mutate(word_len = nchar(word),
         RT = ifelse(participant == "Par_C", RT - 100, #young, so faster
                     ifelse(participant == "Par_G", RT + 200, #old
                            ifelse( participant == "Par_E", RT + 50, #doesnt care about pets
                                    ifelse(participant == "Par_I", RT - 80, #cares about pets
                                           ifelse(participant == "Par_H", RT + 500, #distracted
                                           RT)
                                    )))),
         RT = ifelse(cond == "condB_cat", RT + 210, 
                     ifelse(cond == "practice", RT + 278,
                            ifelse(cond == "condA_cat", RT - 27, 
                                    ifelse(cond == "condA_dog", RT - 113, 
                                           ifelse(cond == "condB_dog", RT + 410, 
                                           RT)
                                    )))),
         RT = ifelse(word_len > 4, RT - 100,
                     ifelse(word_len > 6, RT,
                            ifelse(word_len > 8, RT + 100,
                                   RT + 200))),
         RT = ifelse(RT < 95, runif(n=n(), min=150, max=470), RT),
         X1 = 1:nrow(catdog_spr), 
         RT = round(RT)
                     ) %>% 
  select(X1, participant, item_type, sentence_num, cond, word, RT, full_sentence)

catdog_spr <- catdog_spr  %>%
  group_by(participant, full_sentence) %>%
  mutate(word_num = row_number()) %>%
  ungroup()

participant_data <- tibble(participant = c("Par_A", "Par_B", "Par_C", "Par_D", "Par_E", "Par_F", "Par_G", "Par_H", "Par_I", "Par_J", "Par_K", "Par_M"),
       age = c(24, 28, 18, 32, 36, 25, 21, 68, 34, 22, 28, 33),
       nationality = c("US", "US", "UK", "US", "UK", "UK", "UK", "US", "DE", "UK", "US", "US"),
       pet_interest = c(2, 3, 4, 3, 1, 4, 3, 2, 5, 4, 3, 4),
       gender = c("female","male","female","male","female","female","male","female","nonbinary","male","male","female"),
       education = c(4, 2, 3, 3, 1, 2, 2, 3, 2, 2, 3, 4),
       preference = c("cats", "cats", "dogs", "cats", "cats", "cats", "dogs", "cats", "cats", "dogs", "cats", "dogs"))
  
write_csv(catdog_spr, "data/dgfs_spr.csv")
write_csv(participant_data, "data/dgfs_pars.csv")
```

### Check out that everything looks good

```{r}
ggplot(data=catdog_spr, aes(x=participant, y=RT)) +
  geom_boxplot()
```

```{r}
ggplot(data=catdog_spr, aes(x=cond, y=RT)) +
  geom_boxplot()
```

```{r}
full_data <- participant_data %>% 
  pivot_longer(participant, values_to="participant") %>% 
  full_join(catdog_spr)
```

```{r}
ggplot(data=full_data, aes(x=gender, y=RT)) +
  geom_boxplot()
```

```{r}
full_data %>% 
  group_by(pet_interest) %>% 
  summarize(avg_RT = mean(RT)) %>% 
ggplot(aes(x=pet_interest, y=avg_RT)) +
  geom_col()
```

```{r}
ggplot(data=full_data, aes(x=nationality, y=RT)) +
  geom_boxplot()
```

```{r}
full_data %>% 
  group_by(education) %>% 
  summarize(avg_RT = mean(RT)) %>% 
ggplot(aes(x=education, y=avg_RT)) +
  geom_col()
```


```{r}
mean(catdog_spr$RT)
range(catdog_spr$RT)
```

```{r}
ggplot(data=full_data, aes(x=RT)) +
  geom_histogram(bins = 50) 
```

## Questionnaire
```{r}
animal_survey <- tibble(participant = c("Par_A", "Par_B", "Par_C", "Par_D", "Par_E", "Par_F", "Par_G", "Par_H", "Par_I", "Par_J", "Par_K", "Par_M"),
       age = c(24, 28, 18, 32, 36, 25, 21, 68, 34, 22, 28, 33),
       nationality = c("US", "US", "UK", "US", "UK", "UK", "UK", "US", "DE", "UK", "US", "US"),
       animals_cute = c(2, 4, 4, 3, 1, 5, 4, 3, 5, 5, 3, 4),
       animals_look = c(4, 3, 4, 3, 1, 5, 4, 3, 5, 4, 3, 4),
       animals_pet = c(1, 3, 5, 4, 1, 5, 3, 1, 5, 4, 3, 5),
       animals_have = c(1, 2, 3, 2, 1, 1, 1, 1, 5, 3, 3, 3), # pet interest average of these
       gender = c("female","male","female","male","female","female","male","female","nonbinary","male","male","female"),
       education = c(4, 2, 3, 3, 1, 2, 2, 3, 2, 2, 3, 4),
       cats = c(6, 7, 3, 8, 6, 5, 2, 5, 6, 1, 7, 4),
       dogs = c(3, 2, 8, 4, 3, 2, 7, 3, 3, 8, 3, 6) # preference case when from cats and dogs
       )
```

## Acceptability judgements

```{r}
acc_judge <- tibble(
  "Mary saw a beautiful Siamese cat on her way home from work." = 4.8,
  "Joshua said that purring cats are one of the most relaxing things to him." = 5.3,
  "There was a contented cat looking out from the bookstore window." = 5.1,
  "The child told me that ginger cats are by far the cutest of them all." = 4.9,
  "A large tom cat was often seen hanging out near the butcher shop." = 4.3,
  "My closest neighbor has a guide dog to help him navigate." = 5.5,
  "The students were worried that a mad dog had been spotted in town." = 5.6,
  "Although the barking dog was noisy, he was quite cute." = 5.3,
  "My grandmother had a lap dog that she loved very much." = 5.7,
  "Tracey was the best dog Jenny's family ever had." = 5.3,
  "Lisa has heard of Siamese dogs, but has never seen one." = 3.5,
  "It has been reported that purring dogs are not uncommon." = 1.3,
  "My best friend Jerry has a contented dog that loves to lounge around." = 4.2,
  "On a walk through the woods, Randy saw a ginger dog that was quite regal." = 3.2,
  "The baker said that he saw a tom dog on the loose by the bay." = 1.5,
  "Louise was interested to hear how the guide cat was adapting to his new home." = 1.2,
  "The entire city was talking about a mad cat that was seen digging through trash cans." = 3.9,
  "Poppy read in the newspaper that a barking cat had been identified." = 1.1,
  "The doctor had a lap cat to keep her company after her shifts." = 4.5,
  "Georgie was the best cat that had ever taken part in the contest." = 4.1
)

write_csv(acc_judge, "data/acceptability_judgements.csv")
```


# Exercise data

## Lexical decision 
```{r}
## Design: 
## Lexical decision to either valid R package names, pseudonames, or filler words 
## Cond: participant/not participant
## Outcome: participants faster to real names, slower to pseudonames compared to not participant, filler words same
## 10 true packages / 10 false packages
## 10 true words / 10 foil words
## 40 items total, 20 participants

ld_words <- c("'TidyVerse'",
           "'stringR'",
           "'ggPlot'",
           "'viridis'", 
           "'devtools'",
           "'dPlyr'",
           "'CowPlot'",
           "'recipes'",
           "'reticulate'",
           "'WordCloud2'",
           "'MessyVerse'",
           "'ropeR'",
           "'ggDoodle'",
           "'sirisis'",
           "'ProTips'",
           "'fPlier'",
           "'ChickenPlot'",
           "'stories'",
           "'articulate'",
           "'NumberCloud2'",
           "'interesting'",
           "'freshness'",
           "'Cabinet'",
           "'football'",
           "'Destitude'",
           "'painter'",
           "'throughout'",
           "'realize'",
           "'livelihood'",
           "'Treasure'",
           "'hashtockle'",
           "'voictent'",
           "'dionlize'",
           "'HockLorp'",
           "'parake'",
           "'aplicorter'",
           "'ifringe'",
           "'tablue'",
           "'brazedic'",
           "'Mustord'", 
           "'apple'",
           "'dog'",
           "'trust'",
           "'Program'")

RT <- rep(c(
  rnorm(10, mean=1100, sd= 153), #package_true_no
  rnorm(10, mean=1100, sd= 135), #package_false_no
  rnorm(10, mean=680, sd = 130), #word_true_no
  rnorm(10, mean=999, sd = 112), #word_false_no
  rnorm(4, mean=700, sd = 70), #practice_no
  rnorm(10, mean=500, sd= 253), #package_true_workshop
  rnorm(10, mean=1500, sd= 235), #package_false_workshop
  rnorm(10, mean=680, sd = 130), #word_true_workshop
  rnorm(10, mean=999, sd = 112), #word_false_workshop
  rnorm(4, mean=700, sd = 70) #practice_workshop
  ), 10)


lexicaldec <- tibble(participant = rep(c("AD4", "BH5", "HG8", "LK9", "YU0", "SD2", "RT4", "NG2", "PO9", "JL0", "WS8", "RN4", "XA7", "FG5", "RW1", "KL9", "BN0", "FN3", "YU7", "AQ2"), each = 44),
       order = c(rep("word_package", 44*10), rep("package_word",44 * 10)),
       condB = rep(c(rep("package_true", 10), rep("package_foil", 10), rep("word_true", 10),  rep("word_foil", 10), rep("practice", 4)), 20), 
       condA = rep(c(rep("no_workshop", 44), rep("workshop", 44)), 10),
       item_id = paste("item", rep(1:44, 20), sep="_"), 
       word = rep(ld_words, 20), 
       RT = round(abs(RT))) %>% 
  mutate(item_id = ifelse(item_id %in% c("item_41", "item_42", "item_43", "item_44"), NA, item_id))

lexicaldec <- lexicaldec %>% 
  mutate(word_len = nchar(word),
         RT = ifelse(participant == "KL9", RT - 100, #young, so faster
                     ifelse(participant == "FN3", RT + 200, #old
                            ifelse( participant == "SD2", RT + 50, #doesnt care about pets
                                    ifelse(participant == "AQ2", RT - 80, #cares about pets
                                           ifelse(participant == "NG2", RT + 500, #distracted
                                                  ifelse(participant == "YU0", RT - 200,
                                                         ifelse(participant == "XA7", RT + 120,
                                           RT)))
                                    )))),
         RT = ifelse(word_len > 4, RT - 100,
                     ifelse(word_len > 6, RT,
                            ifelse(word_len > 8, RT + 100,
                                   RT + 200))),
         RT = ifelse(RT < 95, runif(n=n(), min=250, max=999), RT),
         RT = round(RT),
         row = 1:nrow(lexicaldec)) 

participant_lex <- tibble(participant = c("AD4", "BH5", "HG8", "LK9", "YU0", "SD2", "RT4", "NG2", "PO9", "JL0", "WS8", "RN4", "XA7", "FG5", "RW1", "KL9", "BN0", "FN3", "YU7", "AQ2"),
       age = c(24, 28, 18, 32, 36, 25, 21, 68, 34, 22, 28, 33, 45, 23, 19, 29, 37, 41, 28, 29),
       gender = c("female","male","female","male","female","female","male","female","nonbinary","male","male","female", "male", "nonbinary", "female", "female", "male", "female", "male", "male"),
       education = c(4, 2, 3, 3, 1, 2, 2, 3, 2, 2, 3, 4, 5, 3, 2, 4, 1, 2, 3, 5),
       r_interest = c(8, 5, 4, 6, 7, 9, 10, 2, 3, 5, 6, 4, 7, 8, 9, 10, 1, 2, 4, 5))
  
write_csv(lexicaldec, "data/dgfs_lexdec.csv")
write_csv(participant_lex, "data/dgfs_pars_lexdec.csv")
```

```{r}
ggplot(data=lexicaldec, aes(x=condB, y=RT, color= condB)) +
  geom_boxplot()
```

```{r}
ggplot(data=lexicaldec, aes(x=participant, y=RT)) +
  geom_boxplot()
```
